### ISSUE TITLE
Week one?

### ISSUE THREAD

**Issue by shiffman** [shiffman/Intro-ML-Arts-IMA#1]
Due to the Monday / Wednesday schedule and the labor day holiday, this course meets only once the first week (and again Thanksgiving week). I will consider tomorrow an "intro" day and wait to get more into the rhythm of M/W assignments next week? Not 100% sure about this, but thinking out lout as I start to add material.

**Comment by joeyklee** [comment]
@shiffman - I think this makes sense. Maybe it is good to assign a reading and a video/talk about ML that might be interesting for discussion? 

e.g.
+ Viegas & Wattenberg at OpenVisConf 2016 https://www.youtube.com/watch?v=ugkfmHBW74Q 
+ Kyle Macdonald at Kikk 2018: https://vimeo.com/304110435

**Comment by shiffman** [comment]
Thanks, these are great! I'll consider for the specific intro README which I am moving to work on next. Feedback on the outline in #2 is welcome too!

**Comment by joeyklee** [comment]
Super - I'll take a look at #2!

**Comment by ellennickles** [comment]
Viegas & Wattenberg's description of high dimensional space at ~36:00 is so helpful! Noting this for future lessons/discussions.

**Comment by shiffman** [comment]
@joeyklee these are excellent video suggestions I'm adding to the homework for this week in #4!
