### ISSUE TITLE
Drag and Drop Image p5 web editor example for week 2

### ISSUE THREAD

**Issue by shiffman** [shiffman/Intro-ML-Arts-IMA#19]
A note to remake or find this example. See discussion in #15.

**Comment by joeyklee** [comment]
There's also this one https://github.com/ml5js/ml5-homepage-demo!

**Comment by joeyklee** [comment]
https://github.com/ml5js/ml5-homepage-demo

**Comment by shiffman** [comment]
Here's the example!

https://editor.p5js.org/ima_ml/sketches/C5Ywejvuo

@joeyklee we can add this to ml5 if that seems useful .. or just leave it here as an extra example for this course.
