### ISSUE TITLE
Where should this repo live?

### ISSUE THREAD

**Issue by shiffman** [shiffman/Intro-ML-Arts-IMA#3]
I wonder, would this repo make sense in the ml5.js org? I would like to make use of the "team" features to add collaborators. I could also create a new org. The course isn't exclusively ml5, but the goal is to use ml5 as the foundation. any thoughts @joeyklee?

**Comment by joeyklee** [comment]
@shiffman - Oh! I think it doesn't hurt to include it in the ml5 organization. We have already 1 intro workshop repo there, so maybe this is a nice way to start the trend of also adding educational materials to the ml5 cosmos? 

Also yes, the team functions are great for managing this kind of stuff!

**Comment by shiffman** [comment]
Ok, I'm going to move and then create a "team" for collaborating!

**Comment by shiffman** [comment]
Done!
