### ISSUE TITLE
Code snippet generated after the model published.

### ISSUE THREAD

**Issue by peilingjiang** [shiffman/Intro-ML-Arts-IMA#30]
Do we need to add the code snippet displayed after the model is published to our html file? I don't see it in the example and it looks buggy, the copy icon is not working and one end tag </script> is missing. Should we ignore it?

**Comment by shiffman** [comment]
Hi @peilingjiang, thanks for the question!! You can safely ignore the code snippet that Teachable Machine provides! It's a very useful snippet and you may want to explore it later, but for now it's simpler to just use the ml5.js example. Here's the link:

https://editor.p5js.org/ima_ml/sketches/8Wmwnig7-

**Comment by peilingjiang** [comment]
Thank you!
