### ISSUE TITLE
Rubric / Evaluation example for assigning grades + giving feedback

### ISSUE THREAD

**Issue by joeyklee** [shiffman/Intro-ML-Arts-IMA#7]
@shiffman In case you're looking for an example for evaluating student work for the IMA students, here's an example of a rubric that I've found to be very helpful

https://github.com/cmda-tt/course-17-18/tree/master/assessment-1#rubric

**Comment by shiffman** [comment]
Starting to address in #18

**Comment by shiffman** [comment]
The Rubric is available for comments, questions and feedback!

https://github.com/ml5js/Intro-ML-Arts-IMA/blob/source/rubric.md

**Comment by shiffman** [comment]
TODO: add links to the rubric and communicate to the students the criteria over e-mail, in person, and linked from homework.

**Comment by shiffman** [comment]
This is now settled. I'm sure there could be improvements and there will continue to be questions, but further discussion can be in class or in new issues / pull requests / etc!
